import { unified } from "@astrojs/markdown-remark";
import starlight from "@astrojs/starlight";
import { defineConfig } from "astro/config";
import mermaid from "astro-mermaid";
import { fileURLToPath } from "node:url";
import starlightTags from "starlight-tags";
import starlightThemeGalaxy from "starlight-theme-galaxy";
import { SITE_DESCRIPTION, SITE_TITLE, WIKI_ROOT } from "./src/lib/constants";
import { remarkWikiLinks } from "./src/okf/links";

const repository = process.env.GITHUB_REPOSITORY?.split("/")[1];
const customDomain = process.env.CUSTOM_DOMAIN;
const base =
  process.env.BASE_PATH ??
  (process.env.GITHUB_ACTIONS === "true" && repository && !customDomain
    ? `/${repository}`
    : "/");
const site = customDomain
  ? `https://${customDomain}`
  : (process.env.SITE_URL ?? "https://example.github.io");

const wikiRoot = fileURLToPath(new URL(WIKI_ROOT, import.meta.url));

export default defineConfig({
  site,
  base,
  output: "static",
  trailingSlash: "always",
  markdown: {
    // Both `astro-mermaid` and Starlight append their own plugins to this
    // processor, so the OKF link rewriter runs alongside the built-in Markdown
    // pipeline rather than replacing it. It cannot be dropped in favour of
    // Astro's own relative-link resolution: OKF also writes corpus-absolute
    // links (`/sources/page.md`), which Astro leaves untouched.
    processor: unified({
      remarkPlugins: [[remarkWikiLinks, { wikiRoot, base }]],
    }),
  },
  integrations: [
    // Ahead of Starlight so that Starlight extends the processor this replaces,
    // rather than the other way round. Rewrites ```mermaid fences and injects
    // the client renderer, following Starlight's `data-theme` on the way.
    mermaid({ autoTheme: true, enableLog: false }),
    starlight({
      title: SITE_TITLE,
      description: SITE_DESCRIPTION,
      // Corrects sidebar hrefs that plugins emit without the trailing slash
      // `trailingSlash: "always"` requires. See the file for the specifics.
      routeMiddleware: "./src/starlight-route-data.ts",
      plugins: [
        // Overrides Header and ThemeSelect and prepends its own CSS ahead of
        // any `customCss`, so it belongs before plugins that touch those slots.
        starlightThemeGalaxy(),
        // Surfaces the `tags` OKF already writes on every document. `create`
        // rather than the default `warn`: without it the plugin requires a
        // `tags.yml` declaring every tag up front and throws when it is
        // missing, which a corpus that mints new tags on each ingestion run
        // could never keep current. In this mode tags are derived from
        // frontmatter, so a new one needs no config change.
        starlightTags({ onInlineTagsNotFound: "create", sidebar: {} }),
      ],
      // The corpus lives outside `src/content/docs/`, so Starlight has to be
      // told to run its Markdown pipeline (heading anchors, asides) over it.
      markdown: { processedDirs: [WIKI_ROOT] },
      // Autogenerated, but anchored explicitly rather than left to the default.
      // Starlight builds the default sidebar tree by stripping a hardcoded
      // `src/content/docs/` prefix off each entry's `filePath`; ours never has
      // it, so the untrimmed `../../openwiki/…` path became three nested `..`,
      // `..` and `openwiki` groups wrapping the whole wiki. Naming the corpus
      // as the autogenerate directory makes it the prefix that gets stripped.
      // A bare `autogenerate` with no `label` splices the entries in at top
      // level; the labelled form was removed in Starlight v0.39. This still
      // needs no maintenance as the corpus grows — the tree is rebuilt from
      // whatever the last ingestion run left behind.
      sidebar: [{ autogenerate: { directory: WIKI_ROOT } }],
      social: [
        {
          icon: "rss",
          label: "What's new",
          href: `${base.replace(/\/$/, "")}/whats-new/`,
        },
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/seraph1nia/open-ai-wiki",
        },
      ],
    }),
  ],
});
