import { defineConfig } from "vite-plus";

export default defineConfig({
  fmt: {
    // Matches the formatting the repository already had under Prettier, so
    // adopting Oxfmt reflows nothing.
    printWidth: 80,
    // `openwiki/**` is generated by the `openwiki` CLI and rewritten on every
    // scheduled update; formatting it would fight the generator. `changelog/**`
    // is written by `scripts/wiki-changelog.ts` for the same reason: every
    // scheduled run would otherwise land an unformatted fragment. `.astro`
    // files are handled by Prettier (see the `fmt:astro` task) because Oxfmt
    // has no Astro parser.
    ignorePatterns: ["**/.astro/**", "openwiki/**", "changelog/**"],
  },

  lint: {
    ignorePatterns: ["**/.astro/**", "openwiki/**"],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    overrides: [
      {
        files: ["**/*.test.ts"],
        plugins: ["vitest"],
      },
    ],
  },

  test: {
    include: ["apps/*/src/**/*.test.ts", "scripts/**/*.test.ts"],
  },

  run: {
    tasks: {
      // Oxlint and Oxfmt do not parse `.astro`, so the Astro components keep
      // using ESLint + Prettier. Both are scoped to `*.astro` only. The globs
      // stay narrow so the task fingerprint never picks up `dist/`.
      "lint:astro": {
        command: 'eslint "apps/*/src/**/*.astro"',
        input: ["apps/*/src/**/*.astro", "eslint.config.js"],
      },
      "fmt:astro": {
        command: 'prettier --write "apps/*/src/**/*.astro"',
        cache: false,
      },
      "fmt:astro:check": {
        command: 'prettier --check "apps/*/src/**/*.astro"',
        input: ["apps/*/src/**/*.astro", ".prettierrc.json", ".prettierignore"],
      },

      // Deterministic OKF validation of the generated `openwiki/` bundle:
      // frontmatter, source provenance, internal links, anchors and mermaid.
      // Offline and model-free, so it can gate a pull request.
      "lint:wiki": {
        command: "node scripts/wiki-lint.ts",
        input: ["openwiki/**/*.md", "scripts/wiki-lint.ts"],
      },

      // Everything the CI pipeline runs, in order.
      ci: {
        command: [
          "vp check",
          "vp run fmt:astro:check",
          "vp run lint:astro",
          "vp run lint:wiki",
          "vp run -r typecheck",
          "vp test",
          "vp run -r build",
        ],
      },
    },
  },

  staged: {
    "*.{ts,mts,cts,js,mjs,cjs,json}": "vp check --fix",
    "*.astro": ["prettier --write", "eslint --fix"],
  },
});
